apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      containers:
      - name: jenkins
        image: jenkinsci/blueocean
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: vol
          mountPath: /var/run/docker.sock
      volumes:
      - name: vol
        hostPath:
          path: /var/run/docker.sock